import { lazy, type ComponentType, type LazyExoticComponent } from "react";

/**
 * Slug → lazily-loaded tool component.
 *
 * Replaces the eleven registries that each statically imported every tool they
 * knew about. That arrangement produced a single 4.0 MB JavaScript bundle: opening
 * the homepage downloaded all 114 tools plus pdf-lib, pdfjs, xlsx, docx and
 * recharts before anything could render.
 *
 * Each entry here becomes its own Vite chunk, so a visitor downloads the page
 * shell plus exactly one tool. Import specifiers must stay literal strings,
 * Vite needs them statically analysable to split the chunks.
 *
 * Components exported as named bindings are unwrapped into the { default } shape
 * React.lazy requires; the handful exported as defaults are imported directly.
 */
export const lazyToolComponents: Record<string, LazyExoticComponent<ComponentType>> = {
  "audio-cutter": lazy(() => import("@/components/tools/implementations/audio/AudioCutterTool").then((m) => ({ default: m.AudioCutterTool }))),
  "audio-merge": lazy(() => import("@/components/tools/implementations/audio/AudioMergeTool").then((m) => ({ default: m.AudioMergeTool }))),
  "base64-tool": lazy(() => import("@/components/tools/implementations/Base64Tool").then((m) => ({ default: m.Base64Tool }))),
  "box-shadow-generator": lazy(() => import("@/components/tools/implementations/BoxShadowGeneratorTool").then((m) => ({ default: m.BoxShadowGeneratorTool }))),
  "case-converter": lazy(() => import("@/components/tools/implementations/CaseConverterTool").then((m) => ({ default: m.CaseConverterTool }))),
  "chmod-calculator": lazy(() => import("@/components/tools/implementations/ChmodCalculatorTool").then((m) => ({ default: m.ChmodCalculatorTool }))),
  "code-explainer": lazy(() => import("@/components/tools/implementations/CodeExplainerTool").then((m) => ({ default: m.CodeExplainerTool }))),
  "color-converter": lazy(() => import("@/components/tools/implementations/converters/ColorConverterTool").then((m) => ({ default: m.ColorConverterTool }))),
  "color-palette-generator": lazy(() => import("@/components/tools/implementations/ColorPaletteGeneratorTool").then((m) => ({ default: m.ColorPaletteGeneratorTool }))),
  "color-picker": lazy(() => import("@/components/tools/implementations/image/ImageColorPickerTool").then((m) => ({ default: m.ImageColorPickerTool }))),
  "column-extractor": lazy(() => import("@/components/tools/implementations/spreadsheet/ColumnExtractorTool").then((m) => ({ default: m.ColumnExtractorTool }))),
  "cron-expression-builder": lazy(() => import("@/components/tools/implementations/CronExpressionBuilderTool").then((m) => ({ default: m.CronExpressionBuilderTool }))),
  "css-minifier": lazy(() => import("@/components/tools/implementations/CssFormatterTool").then((m) => ({ default: m.CssFormatterTool }))),
  "css-unit-converter": lazy(() => import("@/components/tools/implementations/CssUnitConverterTool").then((m) => ({ default: m.CssUnitConverterTool }))),
  "csv-converter": lazy(() => import("@/components/tools/implementations/csv/CsvConverterTool").then((m) => ({ default: m.CsvConverterTool }))),
  "csv-formatter": lazy(() => import("@/components/tools/implementations/CsvFormatterTool").then((m) => ({ default: m.CsvFormatterTool }))),
  "csv-json-converter": lazy(() => import("@/components/tools/implementations/CsvJsonConverterTool").then((m) => ({ default: m.CsvJsonConverterTool }))),
  "csv-markdown": lazy(() => import("@/components/tools/implementations/converters/CsvMarkdownTool").then((m) => ({ default: m.CsvMarkdownTool }))),
  "csv-merge": lazy(() => import("@/components/tools/implementations/csv/CsvMergeTool").then((m) => ({ default: m.CsvMergeTool }))),
  "csv-to-excel": lazy(() => import("@/components/tools/implementations/spreadsheet/CsvToExcelTool").then((m) => ({ default: m.CsvToExcelTool }))),
  "csv-validator": lazy(() => import("@/components/tools/implementations/csv/CsvValidatorTool").then((m) => ({ default: m.CsvValidatorTool }))),
  "dns-lookup": lazy(() => import("@/components/tools/implementations/DnsLookupTool").then((m) => ({ default: m.DnsLookupTool }))),
  "dockerfile-formatter": lazy(() => import("@/components/tools/implementations/DockerfileFormatterTool")),
  "duplicate-remover": lazy(() => import("@/components/tools/implementations/DuplicateRemoverTool").then((m) => ({ default: m.DuplicateRemoverTool }))),
  "encryption-tool": lazy(() => import("@/components/tools/implementations/EncryptionTool").then((m) => ({ default: m.EncryptionTool }))),
  "env-formatter": lazy(() => import("@/components/tools/implementations/EnvFormatterTool").then((m) => ({ default: m.EnvFormatterTool }))),
  "excel-reader": lazy(() => import("@/components/tools/implementations/spreadsheet/ExcelReaderTool").then((m) => ({ default: m.ExcelReaderTool }))),
  "excel-to-csv": lazy(() => import("@/components/tools/implementations/spreadsheet/ExcelToCsvTool").then((m) => ({ default: m.ExcelToCsvTool }))),
  "fake-data-generator": lazy(() => import("@/components/tools/implementations/FakeDataGeneratorTool")),
  "favicon-generator": lazy(() => import("@/components/tools/implementations/image/FaviconGeneratorTool").then((m) => ({ default: m.FaviconGeneratorTool }))),
  "gitignore-generator": lazy(() => import("@/components/tools/implementations/GitignoreGeneratorTool")),
  "gradient-generator": lazy(() => import("@/components/tools/implementations/GradientGeneratorTool").then((m) => ({ default: m.GradientGeneratorTool }))),
  "gzip-compress": lazy(() => import("@/components/tools/implementations/compression/GzipCompressTool").then((m) => ({ default: m.GzipCompressTool }))),
  "gzip-decompress": lazy(() => import("@/components/tools/implementations/compression/GzipDecompressTool").then((m) => ({ default: m.GzipDecompressTool }))),
  "hash-generator": lazy(() => import("@/components/tools/implementations/HashGeneratorTool").then((m) => ({ default: m.HashGeneratorTool }))),
  "html-entity-encoder": lazy(() => import("@/components/tools/implementations/HtmlEntityEncoderTool").then((m) => ({ default: m.HtmlEntityEncoderTool }))),
  "html-formatter": lazy(() => import("@/components/tools/implementations/HtmlFormatterTool").then((m) => ({ default: m.HtmlFormatterTool }))),
  "html-jsx-converter": lazy(() => import("@/components/tools/implementations/HtmlJsxConverterTool").then((m) => ({ default: m.HtmlJsxConverterTool }))),
  "html-markdown": lazy(() => import("@/components/tools/implementations/converters/HtmlMarkdownTool").then((m) => ({ default: m.HtmlMarkdownTool }))),
  "http-request-composer": lazy(() => import("@/components/tools/implementations/HttpRequestComposerTool")),
  "image-compressor": lazy(() => import("@/components/tools/implementations/image/ImageCompressorTool").then((m) => ({ default: m.ImageCompressorTool }))),
  "image-crop": lazy(() => import("@/components/tools/implementations/image/ImageCropTool").then((m) => ({ default: m.ImageCropTool }))),
  "image-filters": lazy(() => import("@/components/tools/implementations/image/ImageFiltersTool").then((m) => ({ default: m.ImageFiltersTool }))),
  "image-format-converter": lazy(() => import("@/components/tools/implementations/image/ImageFormatConverterTool").then((m) => ({ default: m.ImageFormatConverterTool }))),
  "image-resizer": lazy(() => import("@/components/tools/implementations/image/ImageResizerTool").then((m) => ({ default: m.ImageResizerTool }))),
  "image-rotate-flip": lazy(() => import("@/components/tools/implementations/image/ImageRotateFlipTool").then((m) => ({ default: m.ImageRotateFlipTool }))),
  "image-to-base64": lazy(() => import("@/components/tools/implementations/image/ImageToBase64Tool").then((m) => ({ default: m.ImageToBase64Tool }))),
  "image-watermark": lazy(() => import("@/components/tools/implementations/image/ImageWatermarkTool").then((m) => ({ default: m.ImageWatermarkTool }))),
  "images-to-pdf": lazy(() => import("@/components/tools/implementations/pdf/ImagesToPdfTool").then((m) => ({ default: m.ImagesToPdfTool }))),
  "ip-address": lazy(() => import("@/components/tools/implementations/IpAddressTool")),
  "ip-cidr-calculator": lazy(() => import("@/components/tools/implementations/IpCidrCalculatorTool").then((m) => ({ default: m.IpCidrCalculatorTool }))),
  "json-csv": lazy(() => import("@/components/tools/implementations/converters/JsonCsvTool").then((m) => ({ default: m.JsonCsvTool }))),
  "json-fixer": lazy(() => import("@/components/tools/implementations/JsonFixerTool").then((m) => ({ default: m.JsonFixerTool }))),
  "json-flattener": lazy(() => import("@/components/tools/implementations/JsonFlattenerTool").then((m) => ({ default: m.JsonFlattenerTool }))),
  "json-formatter": lazy(() => import("@/components/tools/implementations/JsonFormatterTool").then((m) => ({ default: m.JsonFormatterTool }))),
  "json-merger": lazy(() => import("@/components/tools/implementations/JsonMergerTool").then((m) => ({ default: m.JsonMergerTool }))),
  "json-minifier": lazy(() => import("@/components/tools/implementations/JsonMinifierTool").then((m) => ({ default: m.JsonMinifierTool }))),
  "json-parse": lazy(() => import("@/components/tools/implementations/JsonParseTool").then((m) => ({ default: m.JsonParseTool }))),
  "json-schema-validator": lazy(() => import("@/components/tools/implementations/JsonSchemaValidatorTool").then((m) => ({ default: m.JsonSchemaValidatorTool }))),
  "json-stringify": lazy(() => import("@/components/tools/implementations/JsonStringifyTool").then((m) => ({ default: m.JsonStringifyTool }))),
  "json-to-excel": lazy(() => import("@/components/tools/implementations/spreadsheet/JsonToExcelTool").then((m) => ({ default: m.JsonToExcelTool }))),
  "json-toml": lazy(() => import("@/components/tools/implementations/converters/JsonTomlTool").then((m) => ({ default: m.JsonTomlTool }))),
  "json-xml": lazy(() => import("@/components/tools/implementations/converters/JsonXmlTool").then((m) => ({ default: m.JsonXmlTool }))),
  "json-yaml": lazy(() => import("@/components/tools/implementations/converters/JsonYamlTool").then((m) => ({ default: m.JsonYamlTool }))),
  "jwt-decoder": lazy(() => import("@/components/tools/implementations/JwtDecoderTool").then((m) => ({ default: m.JwtDecoderTool }))),
  "jwt-generator": lazy(() => import("@/components/tools/implementations/JwtGeneratorTool").then((m) => ({ default: m.JwtGeneratorTool }))),
  "line-break-remover": lazy(() => import("@/components/tools/implementations/LineBreakRemoverTool").then((m) => ({ default: m.LineBreakRemoverTool }))),
  "lorem-ipsum-generator": lazy(() => import("@/components/tools/implementations/LoremIpsumGeneratorTool").then((m) => ({ default: m.LoremIpsumGeneratorTool }))),
  "lz-string-compress": lazy(() => import("@/components/tools/implementations/compression/LzStringCompressTool").then((m) => ({ default: m.LzStringCompressTool }))),
  "markdown-html": lazy(() => import("@/components/tools/implementations/converters/MarkdownHtmlTool").then((m) => ({ default: m.MarkdownHtmlTool }))),
  "markdown-preview": lazy(() => import("@/components/tools/implementations/MarkdownPreviewTool").then((m) => ({ default: m.MarkdownPreviewTool }))),
  "md-to-docx": lazy(() => import("@/components/tools/implementations/converters/MdToDocxTool").then((m) => ({ default: m.MdToDocxTool }))),
  "mime-type-lookup": lazy(() => import("@/components/tools/implementations/MimeTypeLookupTool").then((m) => ({ default: m.MimeTypeLookupTool }))),
  "nginx-config-generator": lazy(() => import("@/components/tools/implementations/NginxConfigGeneratorTool").then((m) => ({ default: m.NginxConfigGeneratorTool }))),
  "number-base-converter": lazy(() => import("@/components/tools/implementations/NumberBaseConverterTool").then((m) => ({ default: m.NumberBaseConverterTool }))),
  "number-formatter": lazy(() => import("@/components/tools/implementations/NumberFormatterTool").then((m) => ({ default: m.NumberFormatterTool }))),
  "password-generator": lazy(() => import("@/components/tools/implementations/PasswordGeneratorTool").then((m) => ({ default: m.PasswordGeneratorTool }))),
  "pdf-compress": lazy(() => import("@/components/tools/implementations/pdf/PdfCompressTool").then((m) => ({ default: m.PdfCompressTool }))),
  "pdf-encrypt": lazy(() => import("@/components/tools/implementations/pdf/PdfEncryptTool").then((m) => ({ default: m.PdfEncryptTool }))),
  "pdf-form-fill": lazy(() => import("@/components/tools/implementations/pdf/PdfFormFillTool").then((m) => ({ default: m.PdfFormFillTool }))),
  "pdf-merge": lazy(() => import("@/components/tools/implementations/pdf/PdfMergeTool").then((m) => ({ default: m.PdfMergeTool }))),
  "pdf-metadata": lazy(() => import("@/components/tools/implementations/pdf/PdfMetadataTool").then((m) => ({ default: m.PdfMetadataTool }))),
  "pdf-reorder": lazy(() => import("@/components/tools/implementations/pdf/PdfReorderTool").then((m) => ({ default: m.PdfReorderTool }))),
  "pdf-rotate": lazy(() => import("@/components/tools/implementations/pdf/PdfRotateTool").then((m) => ({ default: m.PdfRotateTool }))),
  "pdf-sign": lazy(() => import("@/components/tools/implementations/pdf/PdfSignTool").then((m) => ({ default: m.PdfSignTool }))),
  "pdf-split": lazy(() => import("@/components/tools/implementations/pdf/PdfSplitTool").then((m) => ({ default: m.PdfSplitTool }))),
  "pdf-to-images": lazy(() => import("@/components/tools/implementations/pdf/PdfToImagesTool").then((m) => ({ default: m.PdfToImagesTool }))),
  "pdf-unlock": lazy(() => import("@/components/tools/implementations/pdf/PdfUnlockTool").then((m) => ({ default: m.PdfUnlockTool }))),
  "pdf-watermark": lazy(() => import("@/components/tools/implementations/pdf/PdfWatermarkTool").then((m) => ({ default: m.PdfWatermarkTool }))),
  "qr-code-generator": lazy(() => import("@/components/tools/implementations/QrCodeGeneratorTool").then((m) => ({ default: m.QrCodeGeneratorTool }))),
  "regex-generator": lazy(() => import("@/components/tools/implementations/RegexGeneratorTool").then((m) => ({ default: m.RegexGeneratorTool }))),
  "regex-tester": lazy(() => import("@/components/tools/implementations/RegexTesterTool").then((m) => ({ default: m.RegexTesterTool }))),
  "slug-converter": lazy(() => import("@/components/tools/implementations/SlugConverterTool").then((m) => ({ default: m.SlugConverterTool }))),
  "sql-formatter": lazy(() => import("@/components/tools/implementations/SqlFormatterTool").then((m) => ({ default: m.SqlFormatterTool }))),
  "string-escape": lazy(() => import("@/components/tools/implementations/StringEscapeTool").then((m) => ({ default: m.StringEscapeTool }))),
  "svg-png": lazy(() => import("@/components/tools/implementations/converters/SvgPngTool").then((m) => ({ default: m.SvgPngTool }))),
  "text-diff": lazy(() => import("@/components/tools/implementations/TextDiffTool").then((m) => ({ default: m.TextDiffTool }))),
  "text-replacer": lazy(() => import("@/components/tools/implementations/TextReplacerTool").then((m) => ({ default: m.TextReplacerTool }))),
  "text-sorter": lazy(() => import("@/components/tools/implementations/TextSorterTool").then((m) => ({ default: m.TextSorterTool }))),
  "text-to-binary": lazy(() => import("@/components/tools/implementations/TextToBinaryTool").then((m) => ({ default: m.TextToBinaryTool }))),
  "timestamp-converter": lazy(() => import("@/components/tools/implementations/converters/TimestampConverterTool").then((m) => ({ default: m.TimestampConverterTool }))),
  "toml-formatter": lazy(() => import("@/components/tools/implementations/TomlFormatterTool").then((m) => ({ default: m.TomlFormatterTool }))),
  "unicode-inspector": lazy(() => import("@/components/tools/implementations/UnicodeInspectorTool").then((m) => ({ default: m.UnicodeInspectorTool }))),
  "url-encoder": lazy(() => import("@/components/tools/implementations/UrlEncoderTool").then((m) => ({ default: m.UrlEncoderTool }))),
  "url-parser": lazy(() => import("@/components/tools/implementations/converters/UrlParserTool").then((m) => ({ default: m.UrlParserTool }))),
  "user-agent-generator": lazy(() => import("@/components/tools/implementations/UserAgentGeneratorTool")),
  "uuid-generator": lazy(() => import("@/components/tools/implementations/UuidGeneratorTool").then((m) => ({ default: m.UuidGeneratorTool }))),
  "video-metadata": lazy(() => import("@/components/tools/implementations/video/VideoMetadataTool").then((m) => ({ default: m.VideoMetadataTool }))),
  "video-thumbnail": lazy(() => import("@/components/tools/implementations/video/VideoThumbnailTool").then((m) => ({ default: m.VideoThumbnailTool }))),
  "video-to-gif": lazy(() => import("@/components/tools/implementations/video/VideoToGifTool").then((m) => ({ default: m.VideoToGifTool }))),
  "video-trimmer": lazy(() => import("@/components/tools/implementations/video/VideoTrimmerTool").then((m) => ({ default: m.VideoTrimmerTool }))),
  "word-counter": lazy(() => import("@/components/tools/implementations/WordCounterTool").then((m) => ({ default: m.WordCounterTool }))),
  "xml-formatter": lazy(() => import("@/components/tools/implementations/XmlFormatterTool").then((m) => ({ default: m.XmlFormatterTool }))),
  "xml-json-converter": lazy(() => import("@/components/tools/implementations/XmlJsonConverterTool").then((m) => ({ default: m.XmlJsonConverterTool }))),
  "yaml-formatter": lazy(() => import("@/components/tools/implementations/YamlFormatterTool").then((m) => ({ default: m.YamlFormatterTool }))),
  "yaml-json-converter": lazy(() => import("@/components/tools/implementations/YamlJsonConverterTool").then((m) => ({ default: m.YamlJsonConverterTool }))),
  "zip-creator": lazy(() => import("@/components/tools/implementations/archive/ZipCreatorTool").then((m) => ({ default: m.ZipCreatorTool }))),
  "zip-extractor": lazy(() => import("@/components/tools/implementations/archive/ZipExtractorTool").then((m) => ({ default: m.ZipExtractorTool }))),
  "zip-preview": lazy(() => import("@/components/tools/implementations/archive/ZipPreviewTool").then((m) => ({ default: m.ZipPreviewTool }))),
};

export function getLazyTool(slug: string): LazyExoticComponent<ComponentType> | undefined {
  return lazyToolComponents[slug];
}
