// Wrench doubles as the fallback icon and is also a catalog icon, so it is
// imported once as part of the list below.
import type { LucideIcon } from "lucide-react";
import {
  AlignLeft,
  ArrowUpDown,
  Binary,
  Braces,
  Brackets,
  Calculator,
  Calendar,
  CheckCircle,
  Clock,
  Code,
  Code2,
  Columns,
  Container,
  Copy,
  Crop,
  Database,
  Diff,
  Droplets,
  FileCode,
  FileCode2,
  FileDown,
  FileImage,
  FileJson,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileUp,
  Film,
  Fingerprint,
  FolderOpen,
  FolderPlus,
  GitBranch,
  Globe,
  Hash,
  Image,
  Info,
  Inspect,
  Key,
  KeyRound,
  Layers,
  Link,
  List,
  Lock,
  Maximize2,
  Merge,
  MessageCircle,
  Minimize2,
  Network,
  Paintbrush,
  Palette,
  Pipette,
  QrCode,
  Rainbow,
  Repeat,
  Replace,
  RotateCw,
  Ruler,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  Shrink,
  SlidersHorizontal,
  Split,
  Square,
  Star,
  Table,
  Type,
  Users,
  Wand2,
  WrapText,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Every icon referenced by a tool's catalog entry, imported by name.
 *
 * This file exists to replace `import * as Icons from "lucide-react"`. That
 * namespace import is not tree-shakeable: it pulled all ~1,500 lucide icons into
 * the main chunk, 1,547 module references and the single largest contributor to
 * a 1.2 MB entry bundle, even though the catalog only uses 75 of them.
 *
 * Regenerate by collecting the distinct `icon` values across tools.json and
 * toolCatalog.ts. scripts/check-catalog.mjs fails the build if a tool references
 * an icon that is missing here.
 */
const TOOL_ICONS: Record<string, LucideIcon> = {
  AlignLeft,
  ArrowUpDown,
  Binary,
  Braces,
  Brackets,
  Calculator,
  Calendar,
  CheckCircle,
  Clock,
  Code,
  Code2,
  Columns,
  Container,
  Copy,
  Crop,
  Database,
  Diff,
  Droplets,
  FileCode,
  FileCode2,
  FileDown,
  FileImage,
  FileJson,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileUp,
  Film,
  Fingerprint,
  FolderOpen,
  FolderPlus,
  GitBranch,
  Globe,
  Hash,
  Image,
  Info,
  Inspect,
  Key,
  KeyRound,
  Layers,
  Link,
  List,
  Lock,
  Maximize2,
  Merge,
  MessageCircle,
  Minimize2,
  Network,
  Paintbrush,
  Palette,
  Pipette,
  QrCode,
  Rainbow,
  Repeat,
  Replace,
  RotateCw,
  Ruler,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  Shrink,
  SlidersHorizontal,
  Split,
  Square,
  Star,
  Table,
  Type,
  Users,
  Wand2,
  WrapText,
  Wrench,
  Zap,
};

/** Resolves a catalog icon name, falling back to a generic wrench. */
export function getToolIcon(name: string): LucideIcon {
  return TOOL_ICONS[name] ?? Wrench;
}

export function hasToolIcon(name: string): boolean {
  return name in TOOL_ICONS;
}

export const TOOL_ICON_NAMES = Object.keys(TOOL_ICONS);
