import {
  AlertTriangle,
  ArrowDownWideNarrow,
  BookOpen,
  Braces,
  Briefcase,
  Bug,
  Building2,
  Check,
  CloudOff,
  Code2,
  Cog,
  Database,
  Download,
  Eraser,
  FileCheck2,
  FileJson,
  Files,
  FileSearch,
  FileSignature,
  FileText,
  Gauge,
  GraduationCap,
  Infinity as InfinityIcon,
  Keyboard,
  KeyRound,
  Landmark,
  Layers,
  ListChecks,
  ListOrdered,
  Lock,
  LockOpen,
  PenLine,
  Mail,
  Minimize2,
  MoveVertical,
  Network,
  Palette,
  Plane,
  Printer,
  Receipt,
  ScanLine,
  Server,
  Settings2,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Stethoscope,
  Terminal,
  Wand2,
  WifiOff,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/**
 * Curated icon registry for content-driven sections.
 *
 * Deliberately an explicit map instead of `import * as Icons from "lucide-react"`.
 * The namespace import defeats tree-shaking and drags the entire ~1,500 icon set
 * into the bundle, which is a measurable LCP/TBT cost on every page.
 */
const ICONS: Record<string, LucideIcon> = {
  AlertTriangle,
  ArrowDownWideNarrow,
  BookOpen,
  Braces,
  Briefcase,
  Bug,
  Building2,
  Check,
  CloudOff,
  Code2,
  Cog,
  Database,
  Download,
  Eraser,
  FileCheck2,
  FileJson,
  Files,
  FileSearch,
  FileSignature,
  FileText,
  Gauge,
  GraduationCap,
  // Keyed under its plain name; `Infinity` is a JS global, hence the import alias.
  Infinity: InfinityIcon,
  Keyboard,
  KeyRound,
  Landmark,
  Layers,
  ListChecks,
  ListOrdered,
  Lock,
  LockOpen,
  PenLine,
  Mail,
  Minimize2,
  MoveVertical,
  Network,
  Palette,
  Plane,
  Printer,
  Receipt,
  ScanLine,
  Server,
  Settings2,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Stethoscope,
  Terminal,
  Wand2,
  WifiOff,
  Wrench,
  Zap,
};

export function resolveIcon(name: string): LucideIcon {
  return ICONS[name] ?? Wrench;
}
